apiVersion: v1
kind: Namespace
metadata:
  name: testns


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-test
  namespace: testns
  labels:
    deployment: ubuntu-1
spec:
  replicas: 1
  selector:
    matchLabels:
      container: ubuntu-1
  template:
    metadata:
      labels:
        container: ubuntu-1
      annotations:
        container.apparmor.security.beta.kubernetes.io/ubuntu-1-container: localhost/apparmor-demo-ubuntu-1
        kubearmor-policy: enabled
        kubearmor-visibility: process,file,network
    spec:
      containers:
      - name: ubuntu-1-container
        image: 0x010/ubuntu-w-utils:latest
